# Alacritty Configuration
# Source https://github.com/alacritty/alacritty

import = [
  "~/.config/alacritty/default.toml",
]

live_config_reload = true

[font]
size = 11

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[mouse]
hide_when_typing = true

[env]
TERM = "xterm-256color"

[scrolling]
history = 10000
multiplier = 4

[selection]
save_to_clipboard = true

[window.padding]
x = 15
y = 15

[cursor]
style = { shape = "Beam", blinking = "On" }
thickness = 0.15
