[general]
import = [
  "~/dotfiles/alacritty/.config/alacritty/osaka.toml",
]
live_config_reload = true

[window]
opacity = 0.90
padding ={ x = 1, y = 1 }
dynamic_padding = true
decorations = "none"

[font]
normal = {family = "MonaspiceRn Nerd Font", style = "Regular"}
size = 11
bold = {family = "JetBrainsMono Nerd Font", style = "Bold"}

[mouse]
hide_when_typing = true

[scrolling]
history = 50000
multiplier = 4

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "Always" }
thickness = 0.25
