backend = "xrender";
rounded-corners = true;
# corner-radius = 10;
xrender-sync-fence = true;
active-opacity = 1.0;
inactive-opacity = 0.85;
frame-opacity = 0.9;
# Sombras ---
shadow-radius = 8;
shadow-opacity = 0.5;
#fading
# fading = true;
# fade-in-step = 0.10;
# fade-out-step = 0.10;

# Reglas de opacidad
vsync = true;
unredir-if-possible = true;
opacity-rule = [
    "79:class_g = 'Alacritty'",
    "53:class_g = 'Conky'",
    "100:class_g = 'Chromium'",
    "100:class_g = 'firefox'",
    "79:class_g = 'dmenu'",
    "82:class_g = 'float_custom'",
    "90:class_g = 'Rofi'",
    "95:class_g = 'KeePassXC'",
    "90:class_g = 'Spotify'",
    "89:class_g = 'Spacefm'",
    "98:class_g = 'obsidian'",
    "93:class_g = 'Thunar'",
    "93:class_g = 'Session'",
    "91:class_g = 'Nm-connection-editor'",
    "91:class_g = 'Nm-applet'",
    "64:class_g = 'dwm'",
    "90:class_g = 'discord'",
    "94:class_g = 'Desktop'"
];

shadow-exclude = [
  "name = 'Notification'",
  "class_g = 'Conky'",
  "class_g ?= 'Notify-osd'",
  "class_g = 'Cairo-clock'",
];

# detect-rounded-corners = true;
detect-client-opacity = true;
