# Start a terminal
bindsym $mod+Return exec --no-startup-id $terminal

# Launcher (rofi):
bindsym $mod+d exec rofi -show drun

# Launcher (dmenu):
bindsym $mod+Shift+d exec --no-startup-id dmenu_run -fn 'iMWritingDuo Nerd Font-12' -nb '#002B36' -nf '#808080' -sb '#073642' -sf '#ffffff' -p ':' -i

# Kill focused window
bindsym $mod+q kill

# ----- Navigation Settings -----

# Navegación entre ventanas (estilo vim)
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right

# Mover ventanas (estilo vim)
bindsym $mod+Shift+h move left
bindsym $mod+Shift+j move down
bindsym $mod+Shift+k move up
bindsym $mod+Shift+l move right

# Cambiar split horizontal/vertical más intuitivo
bindsym $mod+backslash split h
bindsym $mod+minus split v

# Enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle
# toggle i3bars
bindsym $mod+shift+f bar mode toggle

# Change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# Toggle tiling / floating
bindsym $mod+space floating toggle

# Focus the parent container
bindsym $mod+a focus parent

# Scratchpad
bindsym $mod+x move scratchpad
bindsym $mod+Shift+x scratchpad show



# Reload the configuration file
bindsym $mod+Shift+c reload

# Restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart

mode "resize" {
    bindsym h resize shrink width 10 px
    bindsym j resize grow height 10 px
    bindsym k resize shrink height 10 px
    bindsym l resize grow width 10 px

    bindsym Left resize shrink width 5 px
    bindsym Down resize grow height 5 px
    bindsym Up resize shrink height 5 px
    bindsym Right resize grow width 5 px

    bindsym Return mode "default"
    bindsym Escape mode "default"
}

bindsym $mod+r mode "resize"


# switch to workspace by next or previous
# Cambiar al siguiente workspace
bindsym Mod4+Page_Down workspace next
# Cambiar al workspace anterior
bindsym Mod4+Page_Up workspace prev
# change to workspace like browser style
bindsym $mod+Tab workspace next

bindsym $mod+Shift+Tab workspace prev
