# Startup programs:

# Execute the PolicyKit authentication agent for password entry
exec --no-startup-id /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Start the Gnome Keyring daemon with PKCS#11, secrets, SSH, and GPG support
exec --no-startup-id /usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh,gpg

# Restore wallpaper(Nitrogen) or feh --bg-fill /path/to/wallpaper.jpg
exec --no-startup-id sleep 2 && nitrogen --restore

# exec --no-startup-id picom --config ~/.config/picom/picom.conf
# exec --no-startup-id xfce4-power-manager
