# Floating rules
for_window [class="^(Lxappearance|qalculate-qt|GParted|Blueman-manager|Spek|Gpick|Nitrogen)$"] floating enable
for_window [window_role="^(pop-up|task_dialog)$"] floating enable
for_window [class='firefox' instance='Places'] floating enable

# No borders
for_window [class="^(firefox|Chromium|anytype)$"] border none

# Windows sticky rules
for_window [class="firefox" instance="Toolkit"] sticky enable
for_window [class="guvcview-qt"] sticky enable

# ----- Custom -----
for_window [class="float_custom"] floating enable, resize set 620 450
# ----- Custom -----

# Focus on the urgent window
for_window [urgent=latest] focus